# Category 1
- name: General
  emoji: 💬
  description: General discussion about Img2Num, announcements, or anything off-topic.
  is_answerable: false

# Category 2
- name: Help & Questions
  emoji: ❓
  description: Ask for help, report setup problems, or usage questions.
  is_answerable: true

# Category 3
- name: Feature Ideas
  emoji: 💡
  description: Suggest new features, improvements, or design changes.
  is_answerable: false

# Category 4
- name: Feedback
  emoji: 🧪
  description: Share your thoughts on UI/UX, speed, accuracy, or usability.
  is_answerable: false

# Category 5
- name: Show & Tell
  emoji: 🛠️
  description: Share what you’ve built using Img2Num (demos, screenshots, etc.).
  is_answerable: false

# Category 6
- name: Dev Logs
  emoji: 🧵
  description: Ongoing threads for contributors to share progress or design notes.
  is_answerable: false
