name: Good First Issue
description: A small, approachable task for new contributors.
labels: [good first issue]

body:
  - type: textarea
    attributes:
      label: Task Description
      description: What should be done? Be specific.

  - type: textarea
    attributes:
      label: Files/Components Affected
      description: Where should the contributor look in the codebase?

  - type: textarea
    attributes:
      label: Additional Resources or Hints
      description: Add links or documentation to help newcomers.
